// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv0h6rBE8OobmOUQmh4eQy33sq2dH7jHc',
    appId: '1:764713739072:web:44745bef5e985f676250a5',
    messagingSenderId: '764713739072',
    projectId: 'smart-glove-7b353',
    authDomain: 'smart-glove-7b353.firebaseapp.com',
    storageBucket: 'smart-glove-7b353.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN16qZkJptvdC8J_uCZf8W-eCHpsjW8ls',
    appId: '1:764713739072:android:51b128637ab999a56250a5',
    messagingSenderId: '764713739072',
    projectId: 'smart-glove-7b353',
    storageBucket: 'smart-glove-7b353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByLocXL_CXqHz0EPPRolPzDN_bkQH8ffA',
    appId: '1:764713739072:ios:9ae0ac869cd2b8d66250a5',
    messagingSenderId: '764713739072',
    projectId: 'smart-glove-7b353',
    storageBucket: 'smart-glove-7b353.appspot.com',
    iosBundleId: 'com.example.smartGlove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByLocXL_CXqHz0EPPRolPzDN_bkQH8ffA',
    appId: '1:764713739072:ios:edc4a064bce7c6306250a5',
    messagingSenderId: '764713739072',
    projectId: 'smart-glove-7b353',
    storageBucket: 'smart-glove-7b353.appspot.com',
    iosBundleId: 'com.example.smartGlove.RunnerTests',
  );
}
